table DimDate
	lineageTag: c11916ee-679e-5435-b4ad-a899060aa96c
	dataCategory: Time

	column date
		dataType: dateTime
		isKey
		formatString: dd/mm/yyyy
		lineageTag: 28c4892a-989f-5184-8903-975325cc7993
		summarizeBy: none
		sourceColumn: date

		annotation UnderlyingDateTimeDataType = Date

	column date_key
		dataType: int64
		isHidden
		lineageTag: 31d244c4-5db9-5769-9460-230c125db328
		summarizeBy: none
		sourceColumn: date_key

	column year
		dataType: int64
		lineageTag: fbc11a08-5e33-5cfe-8917-f379dd85662d
		summarizeBy: none
		sourceColumn: year

	column month
		dataType: int64
		lineageTag: 9f3b881f-6561-5603-9f77-2ef44aecb3d9
		summarizeBy: none
		sourceColumn: month

	column month_name
		dataType: string
		lineageTag: 2be3d530-8164-50a8-a704-66b8018fb9e7
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month

	column year_month
		dataType: string
		lineageTag: 15f2af3e-39b7-5e60-a6ed-c29c6d589daa
		summarizeBy: none
		sourceColumn: year_month

	column week_start
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 05c2cc53-92ee-539e-921a-890dc9a67509
		summarizeBy: none
		sourceColumn: week_start

		annotation UnderlyingDateTimeDataType = Date

	column is_weekday
		dataType: int64
		isHidden
		lineageTag: a4ef53bf-830f-5988-972e-7d2877f8afdd
		summarizeBy: none
		sourceColumn: is_weekday

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "DimDate.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    EmptyToNull = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(EmptyToNull, {{"date", type date}, {"date_key", Int64.Type}, {"year", Int64.Type}, {"month", Int64.Type}, {"month_name", type text}, {"year_month", type text}, {"week_start", type date}, {"is_weekday", Int64.Type}}, "en-US")
				in
				    Typed

