"""Execute every query of sql/analysis_queries.sql and write docs/SQL_ANALYSIS_RESULTS.md.

Also writes sql/full_database_dump.sql (schema + data, reproducible).
"""
import re
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / "database" / "klavis_ai_demo.sqlite"


def split_queries(text):
    blocks = re.split(r"^-- (Q\d{2}) (.+)$", text, flags=re.M)
    for i in range(1, len(blocks), 3):
        yield blocks[i], blocks[i + 1].strip(), blocks[i + 2].strip().rstrip(";")


def md_table(cols, rows, limit=15):
    out = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for r in rows[:limit]:
        out.append("| " + " | ".join("" if v is None else str(v).replace("|", "/") for v in r) + " |")
    if len(rows) > limit:
        out.append(f"\n_{len(rows) - limit} more rows not shown._")
    return "\n".join(out)


def main():
    conn = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
    text = (ROOT / "sql" / "analysis_queries.sql").read_text(encoding="utf-8")
    parts = ["# SQL analysis results", "",
             "> Synthetic demonstration data. No real client, legal-case or confidential LexLau/Klavis data is included.",
             "", "Generated by `scripts/run_sql_analysis.py` from `sql/analysis_queries.sql` "
             "on `database/klavis_ai_demo.sqlite` (read-only).", ""]
    n = 0
    for code, title, sql in split_queries(text):
        cur = conn.execute(sql)
        rows = cur.fetchall()
        if not rows:
            raise SystemExit(f"{code} returned no rows")
        cols = [d[0] for d in cur.description]
        parts += [f"## {code} {title}", "", "```sql", sql + ";", "```", "", md_table(cols, rows), ""]
        n += 1
    (ROOT / "docs" / "SQL_ANALYSIS_RESULTS.md").write_text("\n".join(parts), encoding="utf-8")

    with open(ROOT / "sql" / "full_database_dump.sql", "w", encoding="utf-8") as fh:
        fh.write("-- Full dump of database/klavis_ai_demo.sqlite\n")
        fh.write("-- Synthetic demonstration data. No real client, legal-case or confidential "
                 "LexLau/Klavis data is included.\n")
        for line in conn.iterdump():
            fh.write(line + "\n")
    conn.close()
    print(f"{n} analysis queries executed, all returned rows; dump written")


if __name__ == "__main__":
    main()
